name: CI
on:
    push:
        branches:
            - bot
    pull_request:
        branches:
            - bot

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: martinbeentjes/npm-get-version-action@master

            - name: Uses NodeJS v12.18.3
              uses: actions/setup-node@v1
              with:
                  node-version: "12.18.3"

            - name: Install packages
              run: npm install

            - name: Compile Typescript
              run: npm run build

            - name: Delete Useless files
              run: |
                  rm -rf src docs
                  rm copy-files-from-to.json tsconfig.json .gitignore README.md

              #steps.package-version.outputs.current-version
            - name: Script
              uses: actions/github-script@v2
              with:
                  script: |
                      const script = require(`${process.env.GITHUB_WORKSPACE}/scripts/workflow.js`);
                      console.log(script(process.env.RUNNER_TRACKING_ID, "idk", process.env.GITHUB_SHA`, process.env.GITHUB_EVENT_NAME));
                      console.log(JSON.stringify(context), steps ? JSON.stringify(steps) : null)

            - name: Rename gitignore
              run: mv .gitignore.build .gitignore

            - name: Commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git commit -m "Add changes" -a

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: build
                  force: true
