name: CI
on:
    push:
        branches:
            - bot
    pull_request:
        branches:
            - bot

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: martinbeentjes/npm-get-version-action@master

            - name: Uses NodeJS v12.18.3
              uses: actions/setup-node@v1
              with:
                  node-version: "12.18.3"

            - name: Install packages
              run: npm install

            - name: Compile Typescript
              run: npm run build

            - name: Delete Useless files
              run: |
                  rm -rf src docs
                  rm copy-files-from-to.json tsconfig.json .gitignore README.md

            - name: Create README.md
              run: printf "# This is a automatic build of `[bot](https://github.com/zyrouge/news-discord/tree/bot)` branch using Github Actions\n### Build Info\n * Action ID - `${{ secrets.GITHUB_ACTION }}`\n * Version - `${{ steps.package-version.outputs.current-version }}`\n * Commit SHA - `${{ secrets.GITHUB_SHA }}`" README.md

            - name: Rename gitignore
              run: mv .gitignore.build .gitignore

            - name: Push to build branch
              run: |
                  git add .
                  git commit -m "Auto-build"
                  git push --force origin build
