name: CI
on:
    push:
        branches:
            - bot
    pull_request:
        branches:
            - bot

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Uses NodeJS v12.18.3
              uses: actions/setup-node@v1
              with:
                  node-version: "12.18.3"

            - name: Install packages
              run: npm install

            - name: Compile Typescript
              run: npm run build

            - name: Delete Useless files
              run: |
                  rm -rf src docs
                  rm copy-files-from-to.json tsconfig.json .gitignore
                  ls

            - name: Rename gitignore
              run: mv .gitignore.build .gitignore

            - name: Push
              run: |
                  git config --global user.name github-actions
                  git config --global user.email github-actions@github.com
                  git checkout build || git checkout -b build
                  git add build
                  git commit -m "Production Build"
                  git push --force origin build
