name: CI
on:
    push:
        branches:
            - bot
    pull_request:
        branches:
            - bot

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Uses NodeJS v12.18.3
              uses: actions/setup-node@v1
              with:
                  node-version: "12.18.3"

            - name: Install packages
              run: npm install

            - name: Compile Typescript
              run: npm run build

            - name: Delete Useless files
              run: |
                  rm -rf src docs
                  rm copy-files-from-to.json tsconfig.json .gitignore

            - name: Rename gitignore
              run: mv .gitignore.build .gitignore

            - name: Push to built branch
              uses: Automattic/action-commit-to-branch@master
              with:
                  branch: "build"
                  commit_message: "Production Build"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
